mariadb:
  type: mysql
  user: ppf204
  host: 192.168.0.4:3306
  name: ppfinal

kafka:
  brokerList:
    - 192.168.0.2:9092
  topics:
    - syncBuyEventTopic
  group: syncConsumerGroup
  assignor: roundrobin
  verbose: true

redis:
  address: 192.168.0.3:6379
  database: 0
  dialTimeout:  10
  readTimeout:  30
  writeTimeout: 30
  poolSize:     600
  poolTimeout:  30
  cacheExpireTime: 30