mariadb:
  type: mysql
  user: ppf204
  host: 192.168.0.4:3306
  name: ppfinal

kafka:
  brokerList:
    - 192.168.0.2:9092  # used as single broker
  topics:
    - syncBuyEventTopic
  bufferSize: 256
  group: syncConsumerGroup
  assignor: roundrobin
  verbose: true
  flushFrequency: 100  # Millisecond
  ConsumerType: async  # sync or async

redis:
  address: 192.168.0.3:6379
  database: 0
  dialTimeout:  10
  readTimeout:  30
  writeTimeout: 30
  poolSize:     600
  poolTimeout:  30
  cacheExpireTime: 30